---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-demo
parameters:
  type: pd-standard
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Delete
allowVolumeExpansion: false