---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: helloworld-statefulset
spec:
  selector:
    matchLabels:
      app: helloworld-statefulset # has to match .spec.template.metadata.labels
  replicas: 2
  serviceName: helloworld-headless-service
  template:
    metadata:
      labels:
        app: helloworld-statefulset # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
