---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: helloworld-pvc
spec:
  storageClassName: "standard-demo" # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi