---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-deployment
  template:
    metadata:
      labels:
        app: helloworld-deployment
    spec:
      containers:
      - name: busybox
        image: k8s.gcr.io/busybox
        # command: [ "/bin/sh", "-c", "env" ]
        command: ["sleep", "3600"]
        envFrom:
        - secretRef:
            name: helloworld-secret
        volumeMounts:
        - name: data
          mountPath: "/opt/credentials"
      volumes:
      - name: data
        secret:
          secretName: helloworld-secret
          # defaultMode: 0400